# Generated by Django 3.2.2 on 2021-05-27 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 14, 46, 44, 304391), verbose_name='发布日期'),
        ),
    ]
