# Generated by Django 3.2.2 on 2021-05-27 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_publish_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 20, 9, 55, 702241), verbose_name='发布日期'),
        ),
    ]
