# Generated by Django 3.2.2 on 2021-05-27 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210527_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 20, 10, 7, 136753), verbose_name='发布日期'),
        ),
    ]
